[deps]
Changelog = "5217a498-cd5d-4ec6-b8c2-9b85a09b6e3e"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"

[sources]
Documenter = { path = ".." }
